server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie

microservice-porvider-user:
  ribbon:
    # 用于为名为microservice-provider-user的Ribbon客户端设置请求的地址列表
    listOfServers: localhost:8000, localhost:8001
