server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  # 指定数据源
  datasource:
    # 指定数据源类型
    platform: h2
    # 指定h2数据库的建表脚本
    schema: classpath:schema.sql
    # 指定h2数据库的数据脚本
    data: classpath:data.sql
  application:
    name: microservice-provider-user

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    # 将自己的ip注册到Eureka Server
    prefer-ip-address: true


# 配置日志级别，让hibernate打印执行的sql
logging:
  level:
    root: INFO
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descripter.sql.BasicExtractor: trace

# Actuator
management:
  endpoints:
    web:
      exposure:
        # *在yaml文件属于关键字
        include: "*"
  server:
    # 访问的端口
    port: 10111
    servlet:
      # 只有在设置了management.server.port时才有效
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

